name: CD

on:
  workflow_run:
    workflows: [ "CI" ]
    types: [ completed ]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    env:
      PORT: 3000
      APP_MESSAGE: "Hello from CD pipeline!"
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: ~/deploy

      - name: Unzip
        run: |
          cd ~/deploy
          unzip -o app.zip

      - name: Install deps
        working-directory: ~/deploy
        run: npm install --omit=dev

      - name: Run app
        working-directory: ~/deploy
        run: nohup npm start > app.log 2>&1 &
