name: CD

on:
  workflow_run:
    workflows: [ "CI" ]
    types: [ completed ]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    env:
      NODE_ENV: production
      PORT: 3000
      APP_MESSAGE: "Hello from CD on Kali!"

    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Download artifact from CI
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: /home/kali/deploy/node-app
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Unzip artifact
        run: |
          cd /home/kali/deploy/node-app
          unzip -o app.zip

      - name: Install production deps
        working-directory: /home/kali/deploy/node-app
        run: npm ci --omit=dev || npm install --omit=dev

      - name: Write .env (from workflow env)
        working-directory: /home/kali/deploy/node-app
        run: |
          printf "NODE_ENV=%s\nPORT=%s\nAPP_MESSAGE=%s\n" \
            "$NODE_ENV" "$PORT" "$APP_MESSAGE" > .env

      - name: Install & Start with PM2
        working-directory: /home/kali/deploy/node-app
        run: |
          
          # Start or reload the process
          if pm2 describe express-ci-cd-demo >/dev/null 2>&1; then
            pm2 reload express-ci-cd-demo --update-env
          else
            pm2 start index.js --name express-ci-cd-demo
          fi
          pm2 save
        
      - name: Open in browser (if GUI available)
        run: |
            xdg-open "http://localhost:3000" || true
